
format = """
[](username_bg)\
$os\
$username\
[](bg:directory_bg fg:username_bg)\
$directory\
[](fg:directory_bg bg:git_bg)\
$git_branch\
$git_status\
$git_state\
[](fg:git_bg bg:#C9B2D7)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$dotnet\
[](fg:#C9B2D7)\
$docker_context\
$fill\
$time\
$line_break\
$character
"""

add_newline=true
palette="toschi"

[palettes.toschi]
dark_fg="#1d1f21"
username_bg="#2F555B"
directory_bg="#75AFB8"
git_bg="#B2BFD7"
lang_bg="#C9B2D7"

[fill]
symbol = ' '
style = 'bold green'


[character]
success_symbol = '[❯](bold fg:lang_bg)'
error_symbol = '[❯](bold fg:#DA627D)'


[os]
format = '[$symbol]($style)'
style = "bg:username_bg  fg:white"
disabled = false # Disabled by default
[os.symbols]
Arch = "󰣇 "


[username]
show_always = true
style_user = "bg:username_bg fg:white"
style_root = "bg:username_bg"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:directory_bg fg:dark_fg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
[directory.substitutions]
"repos" = "󰳏"
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "



[git_branch]
symbol = ""
style = "bg:git_bg fg:dark_fg"
format = '[ $symbol $branch ]($style)'
[git_status]
style = "bg:git_bg fg:dark_fg"
format = '[$all_status$ahead_behind ]($style)'
[git_state]
style = "bg:#FCA17D fg:#1d1f21"
format = '[\($state( $progress_current of $progress_total)\)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#c5c8c6"
format = '[ $time ]($style)'


## languages
############

[golang]
symbol = " "
style = "bg:lang_bg fg:#1d1f21"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:lang_bg fg:#1d1f21"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:lang_bg fg:#1d1f21"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:lang_bg fg:#1d1f21"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:lang_bg fg:#1d1f21"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:lang_bg fg:#1d1f21"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:lang_bg fg:#1d1f21"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[dotnet]
style = "bg:lang_bg fg:#1d1f21"
symbol= " "
format = '[$symbol ($version) 󰓾 ($tfm)]($style)'
heuristic = true
